"""
Robert Panduru
2018
THis is a demo of the SHA-1 implementation from
hashlib library. The MAC generated by the function
is impossible to reproduce without a huge amount of
processing power if the prefix ie. the key, is unknown.
"""

import hashlib
from random import randint

# Random prefix
def randomKey():
	key = ""
	for i in range(randint(20, 50)):
		key += chr(randint(0, 255))
	return key

key = randomKey()

# Generates the digest of the prefix and the message
def autheticateMessage(message):
	global key
	return hashlib.sha1(key + message).hexdigest()

# These two are very different
print(autheticateMessage("swag"))
print(hashlib.sha1("swag").hexdigest())